***Comments***
This is a template file for feature specific resource file

*** Settings ***
Documentation                   some general description 
Resource                        <common resources only> (eg: ../../RF_core/config.robot)
Variables                       if FEATURE.yaml is relevant and created

*** Keywords ***
Common_keywords1
    <body of keyword>

Common_keywords2
    <body of keyword>